name: 'Gosec Security Scanner'
description: 'Gosec Security Scanner'

runs:
  using: 'composite'
  steps:
    - name: Go mod download
      shell: bash
      run: go mod download

    - name: Check Go Version
      shell: bash
      run: go version

    - name: Install Gosec
      shell: bash    
      run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sudo sh -s -- -b $GOPATH/bin

    - name: Run Gosec Security Scanner
      shell: bash
      run: gosec -exclude G204,G301,G302,G304,G306,G602 -tests -exclude-dir \.*test\.* ./...
