name: "Setup and Cache Go and Configure Private if needed"
description: "Setup and Cache Go 1.25 with automatic GOMODCACHE detection"
inputs:
  gh_token:
    description: "GitHub Personal Access Token"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        cache: false

    - name: Detect GOMODCACHE path
      id: go-cache-paths
      shell: bash
      run: |
        GOMODCACHE=$(go env GOMODCACHE)
        # Fallback to default location if empty
        if [ -z "$GOMODCACHE" ]; then
          GOMODCACHE="$HOME/go/pkg/mod"
        fi
        # Ensure directory exists to prevent cache action warning
        mkdir -p "$GOMODCACHE"
        echo "gomodcache=$GOMODCACHE" >> $GITHUB_OUTPUT

    - name: Detect GOBIN path
      id: go-bin-path
      shell: bash
      run: |
        GOBIN=$(go env GOBIN)
        if [ -z "$GOBIN" ]; then
          GOBIN="$(go env GOPATH)/bin"
        fi
        mkdir -p "$GOBIN"
        echo "path=$GOBIN" >> $GITHUB_OUTPUT

    - name: Go Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.go-cache-paths.outputs.gomodcache }}
        key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-go-

    - name: Go Tools Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.go-bin-path.outputs.path }}
        key: ${{ runner.os }}-${{ runner.arch }}-gotools

    - name: Setup Git Private Module
      if: ${{ inputs.gh_token != '' }}
      shell: bash
      run: git config --global url.https://${{ inputs.gh_token }}@github.com/.insteadOf https://github.com/
