name: 'Setup Local Artifactory'
description: 'Setup Local Artifactory'
inputs:
  RTLIC:
    description: 'Local Artifactory License.'
    required: true
  JFROG_HOME:
    description: 'JFrog Home.'
    required: false
  VERSION:
    description: 'Artifactory Version. Default is latest.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Local Artifactory
      run: |
        go install github.com/jfrog/jfrog-testing-infra/local-rt-setup@main
        if [ -n "${{ env.VERSION }}" ]; then
          ~/go/bin/local-rt-setup --rt-version "$VERSION"
        elif [ "$RUNNER_OS" == "Windows" ]; then
          # Temporary workaround for Windows - Utilize a Specific Version Until the Maven Issue is Fixed   
          ~/go/bin/local-rt-setup --rt-version 7.90.15
        else
          ~/go/bin/local-rt-setup
        fi
      shell: bash
      env:
        RTLIC: ${{ inputs.RTLIC }}
        JFROG_HOME: ${{ inputs.JFROG_HOME }}
        VERSION: ${{ inputs.VERSION }}
