name: 'Setup Local Artifactory'
description: 'Setup Local Artifactory'
inputs:
  RTLIC:
    description: 'Local Artifactory License'
    required: true
  JFROG_HOME:
    description: 'JFrog Home'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Local Artifactory
      run: |
        go install github.com/jfrog/jfrog-testing-infra/local-rt-setup@latest
        # Temporarily use version 7.84.17 due to an issue with the automatic token generation mechanism in 7.90
        ~/go/bin/local-rt-setup --rt-version 7.84.17
      shell: bash
      env:
        RTLIC: ${{ inputs.RTLIC }}
        GOPROXY: direct
        JFROG_HOME: ${{ inputs.JFROG_HOME }}
