name: "Setup Local Artifactory"
description: "Setup Local Artifactory"
inputs:
  RTLIC:
    description: "Local Artifactory License."
    required: true
  JFROG_HOME:
    description: "JFrog Home."
    required: false
  VERSION:
    description: "Artifactory Version. Default is latest."
    required: false
  RT_SETUP_VERSION:
    description: "Version of the local-rt-setup tool. Default is latest."
    required: false
    default: "1.3.7"
  RT_CONNECTION_TIMEOUT_SECONDS:
    description: "Connection timeout for the local Artifactory to be up."
    required: false
    default: "1200"

runs:
  using: "composite"
  steps:
    - name: Install Local Artifactory
      run: |
        go install github.com/jfrog/jfrog-testing-infra/local-rt-setup@${RT_SETUP_VERSION}
        if [ -n "${VERSION}" ]; then
          ~/go/bin/local-rt-setup --rt-version "${VERSION}" --connection-timeout-seconds "${RT_CONNECTION_TIMEOUT_SECONDS}"
        else
          ~/go/bin/local-rt-setup --connection-timeout-seconds "${RT_CONNECTION_TIMEOUT_SECONDS}"
        fi
      shell: bash
      env:
        RTLIC: ${{ inputs.RTLIC }}
        JFROG_HOME: ${{ inputs.JFROG_HOME }}
        VERSION: ${{ inputs.VERSION }}
        RT_SETUP_VERSION: ${{ inputs.RT_SETUP_VERSION }}
        RT_CONNECTION_TIMEOUT_SECONDS: ${{ inputs.RT_CONNECTION_TIMEOUT_SECONDS }}
