name: 'GolangCi Static Code Analysis'
description: 'GolangCi Static Code Analysis'

runs:
  using: 'composite'
  steps:
    - name: Go mod download
      shell: bash
      run: go mod download

    - name: Static Code Analysis
      uses: golangci/golangci-lint-action@v8
      with:
        install-mode: binary
        version: latest
        skip-cache: true
        args: |
          --timeout 5m --enable errcheck,gosimple,ineffassign,staticcheck,unused,gocritic,asasalint,asciicheck,errchkjson,forcetypeassert,makezero,nilerr,unparam,unconvert,wastedassign,usestdlibvars --disable govet
